#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "9b5f6fab3f5543a1b1236b9e338b6646" }
]

[assets]
directory = "./public"
